server:
  port: ${KTP_SERVER_PORT:8090}

mybatis:
  # 告诉 MyBatis 去 resources/mapper 文件夹下找 XML 文件
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    # 这里的 ktp 是你需要在 MySQL 里手动创建的数据库名
    url: ${KTP_DB_URL:jdbc:mysql://127.0.0.1:3306/ktp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8}
    username: ${KTP_DB_USERNAME:root}          # 你的 MySQL 用户名
    password: ${KTP_DB_PASSWORD:}       # 你的 MySQL 密码
    driver-class-name: com.mysql.cj.jdbc.Driver
